[package]
name = "pusoy"
version = "0.1.0"
authors = ["EtomicBomb <ethan@ethan.ws>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
ordered-float = "1.0.2"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
abc = "0.2.3"
rayon = "1.1.0"
num_cpus = "1.10.1"